# Generated by Django 5.1.4 on 2024-12-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batchid', models.PositiveIntegerField(db_column='batchId', max_length=7, primary_key=True, serialize=False)),
                ('coursename', models.CharField(blank=True, db_column='courseName', max_length=15, null=True)),
                ('joinyear', models.IntegerField(blank=True, db_column='joinYear', max_length=4, null=True)),
                ('endyear', models.IntegerField(blank=True, db_column='endYear', max_length=4, null=True)),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='OfficialAlumni',
            fields=[
                ('regno', models.PositiveIntegerField(db_column='regNo', primary_key=True, serialize=False)),
                ('studentname', models.CharField(db_column='studentName', max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('instmail', models.EmailField(blank=True, db_column='instMail', max_length=23, null=True)),
                ('personalmail', models.EmailField(blank=True, db_column='personalMail', max_length=40, null=True)),
                ('batchid', models.ForeignKey(blank=True, db_column='batchId', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.batches')),
            ],
            options={
                'db_table': 'official_alumni',
                'managed': True,
            },
        ),
    ]
