# Generated by Django 5.1.4 on 2025-01-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialalumni',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officialalumni',
            name='batchid',
            field=models.ForeignKey(db_column='batchId', on_delete=django.db.models.deletion.PROTECT, to='core.batches'),
        ),
        migrations.AlterField(
            model_name='officialalumni',
            name='personalmail',
            field=models.EmailField(blank=True, db_column='personalMail', max_length=255, null=True),
        ),
    ]
