# Generated by Django 5.1.4 on 2025-01-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_officialalumni_is_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialalumni',
            name='is_registered',
        ),
    ]
