# Generated by Django 5.1.4 on 2025-01-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_officialalumni_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialalumni',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
