# Generated by Django 5.1.4 on 2025-01-16 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mailVerification',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('otp', models.CharField(default='475419', max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=datetime.datetime(2025, 1, 17, 18, 30, 19, 170596, tzinfo=datetime.timezone.utc), editable=False)),
            ],
        ),
    ]
